name: Build Packages

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  actions: write

jobs:
  build-arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm rust cargo git
      - name: Build package
        run: |
          useradd builder -m
          chown -R builder:builder .
          sudo -u builder makepkg -s --noconfirm
      - name: Upload Arch Package
        uses: actions/upload-artifact@v4
        with:
          name: arch-package
          path: ./*.pkg.tar.zst

  build-deb:
    runs-on: ubuntu-latest
    container:
      image: debian:sid
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential git debhelper pkg-config libssl-dev cargo rustc
      - name: Build package
        run: |
          dpkg-buildpackage -us -uc
      - name: Move Debian Package
        run: |
          mv ../*.deb ./
      - name: Upload Debian Package
        uses: actions/upload-artifact@v4
        with:
          name: debian-package
          path: ./*.deb

  build-rpm:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
      options: --privileged
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf install -y rust cargo git rpm-build rpmdevtools openssl-devel pkg-config
      - name: Build package
        run: |
          mkdir -p ~/rpmbuild/{SOURCES,SPECS}
          cp git-commit-helper.spec ~/rpmbuild/SPECS/
          tar --transform 's,^,git-commit-helper-0.1.0/,' -czf ~/rpmbuild/SOURCES/git-commit-helper-0.1.0.tar.gz *
          rpmbuild -ba ~/rpmbuild/SPECS/git-commit-helper.spec
      - name: Upload RPM Package
        uses: actions/upload-artifact@v4
        with:
          name: rpm-package
          path: ~/rpmbuild/RPMS/x86_64/*.rpm

  build-binary:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: ".exe"
          - os: macos-latest
            target: x86_64-apple-darwin
            suffix: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: Build Binary
        run: |
          cargo build --release --target ${{ matrix.target }}
      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: git-commit-helper-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/git-commit-helper${{ matrix.suffix }}

  create-release:
    needs: [build-arch, build-deb, build-rpm, build-binary]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            arch-package/*.pkg.tar.zst
            debian-package/*.deb
            rpm-package/*.rpm
            git-commit-helper-x86_64-unknown-linux-gnu/git-commit-helper
            git-commit-helper-x86_64-pc-windows-msvc/git-commit-helper.exe
            git-commit-helper-x86_64-apple-darwin/git-commit-helper
