name: Build Packages

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build-arch:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm rust cargo git
      - name: Build package
        run: |
          useradd builder -m
          chown -R builder:builder .
          sudo -u builder makepkg -s --noconfirm
      - name: Upload Arch Package
        uses: actions/upload-artifact@v3
        with:
          name: arch-package
          path: ./*.pkg.tar.zst

  build-deb:
    runs-on: ubuntu-latest
    container: debian:stable
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl build-essential git debhelper
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Build package
        run: |
          export PATH="$HOME/.cargo/bin:$PATH"
          dpkg-buildpackage -us -uc
      - name: Upload Debian Package
        uses: actions/upload-artifact@v3
        with:
          name: debian-package
          path: ../*.deb

  build-rpm:
    runs-on: ubuntu-latest
    container: fedora:latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          dnf install -y rust cargo git rpm-build rpmdevtools
      - name: Build package
        run: |
          mkdir -p ~/rpmbuild/{SOURCES,SPECS}
          cp git-commit-helper.spec ~/rpmbuild/SPECS/
          tar czf ~/rpmbuild/SOURCES/git-commit-helper-0.1.0.tar.gz .
          rpmbuild -ba ~/rpmbuild/SPECS/git-commit-helper.spec
      - name: Upload RPM Package
        uses: actions/upload-artifact@v3
        with:
          name: rpm-package
          path: ~/rpmbuild/RPMS/x86_64/*.rpm

  create-release:
    permissions:
      contents: write
    needs: [build-arch, build-deb, build-rpm]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            arch-package/*.pkg.tar.zst
            debian-package/*.deb
            rpm-package/*.rpm